[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/"
  to = "/lms-samisi/login"
  status = 301
  force = true

[[redirects]]
  from = "/login"
  to = "/lms-samisi/login"
  status = 301
  force = true
